
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18 AS builder

WORKDIR /build
COPY . .
RUN make ccm-linux

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9

LABEL description="Alibaba Cloud Controller Manager"

COPY --from=builder /build/build/bin/cloud-controller-manager.amd64 /bin/alibaba-cloud-controller-manager

ENTRYPOINT [ "/bin/alibaba-cloud-controller-manager" ]
