
FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10 as builder

WORKDIR /build
COPY . .
RUN make ccm-linux

FROM registry.ci.openshift.org/ocp/4.9:base

LABEL description="Alibaba Cloud Controller Manager"

COPY --from=builder /build/build/bin/cloud-controller-manager.amd64 /bin/alibaba-cloud-controller-manager

ENTRYPOINT [ "/bin/alibaba-cloud-controller-manager" ]
